puppetlabs/puppet-lint

lib/puppet-lint/plugins/check_strings/double_quoted_strings.rb
spec/puppet-lint/plugins/check_strings/double_quoted_strings_spec.rb

Prior to this commit, if the `\s` escape sequence was used, this
would cause a F+ from the `double_quoted_strings` check.
This commit updates the `double_quoted_string` check to permit the
`\s` string literal.
Resolves: #16

(GH-16) Do not warn on "\s" string literal

---

lib/puppet-lint.rb
lib/puppet-lint/configuration.rb
lib/puppet-lint/report/github.rb
spec/puppet-lint/configuration_spec.rb
spec/spec_helper.rb

It is possible to get inline annotations with GitHub Actions. This is based on Rubocop's formatter.
It's implemented as a configuration option that's dynamic by default. This means it will show up in actions, but not in other environments. Overriding is still possible.

Add GitHub Actions annotations

---

lib/puppet-lint.rb

The output does not mix well. This does mean the PDK can't use these annotations, but at least it doesn't break it either.

Don't print GitHub annotations in JSON mode

---

lib/puppet-lint/tasks/release_test.rb

This PR adds a few modules that are tested during a puppet-lint CI run.
Those are modules from the community with a lot of Puppet Code/activity.

Extend tested-modules in CI

---

spec/spec_helper.rb

The CI only runs on Ruby 2.4, 2.5 and 2.7.

Reenable coverage reports

---

lib/puppet-lint/checkplugin.rb

Prior to this commit puppet-lint did not expose the following methods from `PuppetLint::Data`:
* `array_indexes`
* `hash_indexes`
* `defaults_indexes`
* `function_indexes`
This commit adds public methods to `PuppetLint::CheckPlugin` so that the methods above are accessible from puppet-lint plugins.
Fixes #47

(GH-47) Expose additional indexes

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/release_prep.yml

Concept PR to demonstrate reusable actions

(MAINT) Add CI and release workflows

---

.github/workflows/labeller.yml

This PR introduces the community labeller action. It's purpose is to appropriately label community issues and PRs.

(MAINT) Add community labeller

---

.github/workflows/ci.yml

Prior to this commit the triggers for the ci workflow were set to `master`. This modules default branch has now moved to `main` meaning that the triggers are invalid.
This commit updates the triggers to `main` so that workflows are correctly triggered on pushes and pull requests.

(MAINT) Update CI trigger

---

lib/puppet-lint/plugins/check_whitespace/140chars.rb
lib/puppet-lint/plugins/check_whitespace/80chars.rb

Prior to this commit a rubocop was still generating suggestions for the two line length checks. This was because there was missing whitespace around the `+` operand.
This commit adds the space to satisfy rubocop.

(MAINT) Fix spacing issue

---

Dockerfile

Prior to this PR the docker build process fails with:
`Error: unable to select packages`
This commit fixes the above by using the official ruby image and pinning the version to 2.7.
While this PR fixes a bug, it does not actually change the code so it has been labeled as `maintenance`.

(GH-42) Fix Dockerfile

---

puppet-lint.gemspec

This commit adds .rubocop.yml as a required file in the gemspec. This is so that other puppet-lint plugins can inherit a common set of rules.
Ultimately this could make navigating the landscape easier if coding style is simiar.

(MAINT) Add rubocop config to gemspec

---

Gemfile

Prior to this PR the version of rake installed with this project was vulnerable to an OS command injection attach.
The CVE ID for this is: CVE-2020-8130
This PR fixes the above by removing the version constraint and ensuring that the latest version of rake is always pulled.

(MAINT) Remove version constraint for rake

---

puppet-lint.gemspec

This commit corrects a regression caused by the removal of `spec/**/*',` in the gemspec.
As noted by @ekohl in #60, it would break every plugin due to the consumption of the spec helpers from puppet-lint.

(MAINT) Restore spec files in gems

---

lib/puppet-lint/plugins.rb
spec/spec_helper.rb

This allows plugins to work again. See individual commits for details.
Fixes https://github.com/puppetlabs/puppet-lint/issues/65

Fix plugin regressions introduced in 3.0.0

---

lib/puppet-lint/version.rb

This commit bumps the puppet-lint gem version to 3.0.1.

(MAINT) Bump gem version to 3.0.1

---

README.md

This PR updates the compatibility message in the README so it is clear to users that Puppet Lint version 3.x and above will no longer support Puppet 6 environments.

(MAINT) Update Compatibility Message

---

puppet-lint.gemspec

Fixes: 7f67d8cdb30ddc6efef9333c11e49a530197cee3

Remove spurious quote in gem description

---

spec/unit/puppet-lint/bin_spec.rb

In 21f5743521fe36f4cc04f87ea62b63d9b5a9567e the output was changed and the code path when rspec-json_expectations is present was updated, but not without. While this is an odd code path (since Gemfile does declare it as a dependency), it can be hit if a different dependency mechanism is used (in particular: run the test suite in RPM's %check phase with explicit BuildRequires) and the expectations should be correct.
Fixes: 21f5743521fe36f4cc04f87ea62b63d9b5a9567e

Fix assertion when rspec-json_expectations is missing

---

_config.yml
_layouts/default.html
checks/index.md
developer/api/index.md
developer/tutorial/index.md
index.md
plugins/index.md

Currently all the links in github pages are broken, I am hoping this update should make the links functional

Updating doc links to centre on puppet-lint to work on githubpages

---

puppet-lint.gemspec

To make puppet-lint more accessible and usable in Puppet 6 environments, this commit lowers the required Ruby version to 2.5.

(CONT-339) Lower Ruby requirement

---

lib/puppet-lint/plugins/top_scope_facts/top_scope_facts.rb
spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb

This commit introduces the top_scope_facts check.
The plugin originated here:
https://github.com/mmckinst/puppet-lint-top_scope_facts-check
and was authored by @mmckinst and @seanmil.
Permission has been given to migrate this check to the puppet-lint default plugin set in this PR:
https://github.com/mmckinst/puppet-lint-top_scope_facts-check/pull/11

(CONT-339) Add top scope facts check

---

lib/puppet-lint/plugins/check_whitespace/trailing_whitespace.rb
spec/unit/puppet-lint/plugins/check_whitespace/trailing_whitespace_spec.rb

Continuing work from https://github.com/puppetlabs/puppet-lint/pull/83 by adding tests
Resolves https://github.com/puppetlabs/puppet-lint/issues/81

Fix first token whitespace

---

lib/puppet-lint/plugins/legacy_facts/legacy_facts.rb
spec/unit/puppet-lint/plugins/legacy_facts/legacy_facts_spec.rb

This change adds the Legacy Facts check originally authored by @mmckinst.
Additional contributions to the check were made by @seanmil, @rodjek, @baurmatt, @bart2 and @joshcooper

(CONT-670) Add legacy facts check

---

lib/puppet-lint/data.rb
spec/unit/puppet-lint/data_spec.rb

This PR updates the `resource_indexes` method so that it will skip CLASSREF tokens.
For more background on this PR please see [#31](https://github.com/voxpupuli/puppet-lint-trailing_comma-check/issues/31)

(CONT-666) Skip classref types

---

lib/puppet-lint/plugins/legacy_facts/legacy_facts.rb
spec/unit/puppet-lint/plugins/legacy_facts/legacy_facts_spec.rb

Prior to this change the legacy facts check would not detect legacy facts defined as follows:
```
$::facts['osfamily']
````
This changes updates the `check` logic to evaluate tokens that may start with `::` and extract the fact name as appropriate. `

(CONT-675) Fix fact detection

---

README.md
lib/puppet-lint.rb
lib/puppet-lint/bin.rb
lib/puppet-lint/configuration.rb
lib/puppet-lint/optparser.rb
lib/puppet-lint/report/codeclimate.rb
lib/puppet-lint/tasks/puppet-lint.rb
spec/fixtures/test/reports/code_climate.json
spec/unit/puppet-lint/bin_spec.rb
spec/unit/puppet-lint/configuration_spec.rb

An alternative to https://github.com/puppetlabs/puppet-lint/pull/78
Once/if this is accepted, I'll open a pdk-templates PR to add support there.

codeclimate (GitLab Code Quality compatible) output support 

---

.github/workflows/release_prep.yml

Prior to this PR, the version of the gem would need to be manually updated, pushed and merged into main each time before running release_prep.yml.
This PR introduces a "version" input parameter, that can be specified when running the workflow which eliminates the need for the above.

(CONT-233) - Add version input to gem_release_prep.yml

---

README.md
lib/puppet-lint/checks.rb

Prior to this commit the URL directed to an old issues tab.
This PR updates the URL to direct reporters to the correct tab.

(maint) Update issues URL

---

lib/puppet-lint/plugins/legacy_facts/legacy_facts.rb
spec/unit/puppet-lint/plugins/legacy_facts/legacy_facts_spec.rb

Do not crash when referring to a fact key without quoting it

---

Gemfile

Prior to this commit, a bundle install on some systems failed due to Gemfile conflicts arising from the changelog generator gem. This commit pins it to v1.15.0
Provide a detailed description of all the changes present in this pull request.

(CAT-1301) Pin changelog generator gem

---

README.md

Removed outdated compatability warning since Puppet 6 is not supported by any tool. Added development section taken from https://github.com/puppetlabs/puppetlabs-concat#development detailing how users can run acceptance tests, raise PRs/Issues and contact support
Provide a detailed description of all the changes present in this pull request.

(CAT-1434) Update README

---

rubocop_baseline.yml

This PR fixes CI by excluding the soon-to-be deprecated [Rspec/FilePath](<https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FilePath>).  
During investigation and after running ``bundle exec rubocop --format github`` 2 simultaneous warnings were observed ``Rspec/FilePath`` (deprecated) and ``Rspec/SpecFilePathFormat``:
```
::error file=spec/unit/puppet_lint/puppet-lint_spec.rb,line=1,col=1::RSpec/SpecFilePathFormat: Spec path should end with `puppet_lint*_spec.rb`. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/SpecFilePathFormat)
::error file=spec/unit/puppet_lint/puppet-lint_spec.rb,line=5,col=1::RSpec/FilePath: Spec path should end with `puppet_lint*_spec.rb`. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FilePath)
➜
```
The warning seem to …

(CAT-1488) - Fix rubocop warnings

---

spec/unit/puppet-lint/plugins/check_classes/variable_scope_spec.rb
spec/unit/puppet-lint/plugins/check_whitespace/arrow_alignment_spec.rb
spec/unit/puppet-lint/plugins/legacy_facts/legacy_facts_spec.rb

Was unable to find much that needed to be updated with the majority of the outdated code references existing within the legacy fact tests.

(CAT-1435) Address outdated code

---

puppet-lint.gemspec

Gem is to be re-published under the name `puppetlabs-puppet-lint` in order to fully move it under the ownership of `Puppet`.
Author is not being touched.

(CAT-1248) Update Published Name and Owner

---

lib/puppet-lint/version.rb
puppet-lint.gemspec

Rolling back release v5.0.0.
Releasing puppet-lint gem with reference to newly published rubygem on GitHub registry.
Have added original owner back as this will be the final release under https://rubygems.org/gems/puppet-lint.

(maint) - Release prep v4.2.2

---

lib/puppet-lint.rb
lib/puppet-lint/checks.rb
lib/puppet-lint/configuration.rb
lib/puppet-lint/optparser.rb
lib/puppet-lint/tasks/puppet-lint.rb

Prior to this commit, on an unexpected rubocop update, some of our repositories started highlighting errors for new rubocop rules. This has caused our CI to fail.
This commit aims to address these failures.

(CAT-1653) Fix Rubocop issues

---

.github/workflows/ci.yml
Gemfile
Rakefile
spec/spec_helper.rb

Provide a detailed description of all the changes present in this pull request.

(CAT-1618) - Add code coverage back to ci

---

lib/puppet-lint/plugins/top_scope_facts/top_scope_facts.rb
spec/unit/puppet-lint/plugins/top_scope_facts/top_scope_facts_spec.rb

Prior to this PR, if you had a top scope structured fact like this in your manifest `$::my_structured_fact['foo']['test']`, lint would return an invalid correction when passed the fix flag.
Now, we have altered the top_scope_facts plugin, to first check if it is a structured fact, and if one is found using regex, apply different logic to fix.
Unstructured top scope fact:
```
$foo = $::my_structured_fact
```
when fixed:
```
bundle exec puppet-lint ./manifest.pp -f
FIXED: top scope fact instead of facts hash on line 1 (check: top_scope_facts)
```
```
$foo = $facts['my_structured_fact']
```
top scope structured fact (& not on allowlist):
```
$foo = $::my_structured_fact['foo']['test']
```
when fixed:
```
bundle exec puppet-lint ./manifest.pp -f
FIXED: top scope fact instead of facts hash on …
```

(GH-189) - invalid fact correction for top scope structured fact

---

spec/unit/puppet-lint/lexer_spec.rb

Prior to this the following error occurred:  ``RSpec/DescribedClass: Use `described_class` instead of `PuppetLint::Lexer`. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/DescribedClass)``
Provide a detailed description of all the changes present in this pull request.

Fix RSpec/DescribedClass warning

---

Gemfile
lib/puppet-lint/lexer/token.rb
lib/puppet-lint/tasks/puppet-lint.rb
rubocop_baseline.yml

Reverts puppetlabs/puppet-lint#203

Revert "(maint) Exclude breaking rubocop versions"

---

lib/puppet-lint/data.rb

Currently, the method `function_indexes` in `lib/puppet-lint/data.rb` doesn't work and only returns empty arrays. This is because, when iterating over the `token` array, tokens are skipped if their type does not equal `:NAME` but tokens that represent function call declarations have the type `:FUNCTION_NAME` and are skipped during iteration.
Steps to reproduce:
1. Create a basic puppet-lint plugin gem.
2. In a `lib/puppet-lint/plugins/<what ever your plugin name is>.rb` file, add `require 'pry'; binding.pry` as the first line in the plugin's `#check` method definition.
3. Create (or edit) the RSpec test for the plugin ensure that the `:code` block that your plugin test will execute against has a Puppet function call in it (i.e. `notice('This is the func')`)
4. Run RSpec. When the pry …

Fix function call name token type in function_indexes method

---

lib/puppet-lint/lexer.rb
spec/unit/puppet-lint/lexer_spec.rb

Error type wasn't known to the lexer. That makes puppet-lint to fire `unquoted_string_in_{selector|case}` on this type check.
Consider this code:
```puppet
$x ? {
Error => false,
default => true,
}
```
Puppet-lint will raise a warning on the line containing the Error.

Add Error type to the lexer tokens (and sort them)

---

lib/puppet-lint/lexer.rb
spec/unit/puppet-lint/lexer_spec.rb

Same issue as with Error in https://github.com/puppetlabs/puppet-lint/pull/216

Add Binary type to lexer type tokens list

---

.rubocop_todo.yml
lib/puppet-lint/optparser.rb
spec/fixtures/test/manifests/top_scope_variables.pp
spec/unit/puppet-lint/bin_spec.rb

This adds the ` --top-scope-variables` CLI option that sets `PuppetLint.configuration.top_scope_variables`.
#228

add --top-scope-variables cli argument, fix #228

---

lib/puppet-lint/bin.rb
lib/puppet-lint/checks.rb
lib/puppet-lint/plugins/legacy_facts/legacy_facts.rb
spec/unit/puppet-lint/checks_spec.rb
spec/unit/puppet-lint/plugins/legacy_facts/legacy_facts_spec.rb

With this PR puppet_lint will now be able to do legacy fact checks in yaml files. 
I’ve limited checks to legacy facts for yaml and no auto-fixing.
Here is a test yaml file I tested against:  
```yaml
---
version: 5
defaults:  # Used for any hierarchy level that omits these keys.
datadir: data         # This path is relative to hiera.yaml's directory.
data_hash: yaml_data  # Use the built-in YAML backend.
hierarchy:
- name: "LEGACY FACT PATH"
paths:
- "os/%{facts.hostname}.yaml"
- "/var/www/%{::hostname}.yaml"
- "%{::bios_vendor}.yaml"
- name: "osfamily/major release"
paths:
- "os/%{facts.os.name}/%{facts.os.release.major}.yaml"
- name: 'common'
path: 'common.yaml'
```
After running puppet-lint on this file puppet-lint will correctly flag any legacy_facts warnings:
```console …
```

Extend puppet-lint to legacy_check yaml files

---

lib/puppet-lint/checks.rb
spec/acceptance/puppet_lint_spec.rb
spec/fixtures/test/manifests/parseable.yaml
spec/unit/puppet-lint/checks_spec.rb

The new feature of checking YAML files chokes on valid YAML files; this change attempts to mitigate that problem.
PR #235 added scanning of YAML files to puppet-lint; to my surprise, my CI started failing with a number of syntax errors that hadn't been there before.  Digging into it, it seems to be because the YAML files get fed through `PuppetLint::Lexer`, which doesn't handle some YAML literals correctly (and, being designed for Puppet manifests, I wouldn't expect it to).
Note that a YAML file as included in the change is parsed fine by Psych and yamllint, but puppet-lint chokes on it because it gets fed through the manifest lexer first, which can't cope with some things that are valid YAML.  I have larger examples but this was the smallest reduction I could make that still failed. …

Avoid using the manifest lexer on YAML
